package housetaxes;

public enum ServiceType {
    CHARITY, WATTER_SUPPLY, GAS_COMPANY, OTHERS, ELECTRICITY, ELECTRICITY_ENTRY,
    INSURANCE_AND_FINANCIAL_SERVICES, INTERNET_SERVICES, SATELLITE_CABLE_TELEVISION,
    EDUCATION, LOAN_GRANTING, PROFESSIONAL_HOME_MANAGER, SIGNALING_SECURITY_EQUIPMENT_AND_SERVICES,
    TELECOMMUNICATION_SERVICES, THERMAL_ENERGY
}
